services:
  account-service:
    build:
      context: .
      dockerfile: backend/services/account-service/Dockerfile
    env_file:
      - ./backend/services/account-service/.env
    develop:
      watch:
        - action: sync+restart
          path: ./backend/services/account-service/src/account_service
          target: /app/backend/services/account-service/src/account_service
        - action: sync+restart
          path: ./backend/infra
          target: /app/backend/infra
        - action: rebuild
          path: ./backend/services/account-service/pyproject.toml
        - action: rebuild
          path: ./backend/services/account-service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:16-alpine
    #profiles: ["postgres"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_service"]
      interval: 5s
      timeout: 3s
      retries: 5
