from typing import Protocol, Sequence

from datetime import datetime
from uuid import UUID

from account_service.domain.entities.permission import Permission
from account_service.domain.entities.role import Role
from account_service.domain.entities.session import Session
from account_service.domain.entities.user import User


class UserRepositoryPort(Protocol):
    async def create(self, user: User) -> User: ...

    async def get(self, user_id: UUID) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def list(self) -> Sequence[User]: ...

    async def update(self, user: User) -> User: ...

    async def delete(self, user_id: UUID) -> None: ...


class SessionRepositoryPort(Protocol):
    async def create(self, session: Session) -> Session: ...

    async def get(self, session_id: UUID) -> Session | None: ...

    async def rotate(self, session_id: UUID, token_id: str, expires_at: datetime) -> None: ...

    async def revoke(self, session_id: UUID) -> None: ...


class AuthorizationRepositoryPort(Protocol):
    async def ensure_defaults(self) -> None: ...

    async def get_role_by_key(self, key: str) -> Role | None: ...

    async def get_permission_by_key(self, key: str) -> Permission | None: ...

    async def role_has_permission(self, role_key: str, permission_key: str) -> bool: ...
